from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from .model import Connection, Design, Instance, Module, Net, Port
from .verilog_util import file_name_for_hierarchy, module_name_for_hierarchy, resolve_port_width, sanitize_identifier, width_range


@dataclass
class Adaptation:
    decls: list[str] = field(default_factory=list)
    assigns: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    port_net: str | None = None


def emit_verilog(design: Design, output_dir: str | Path, top: str = "top") -> list[Path]:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    files = []
    for hierarchy in _all_hierarchies(design, top):
        text = _emit_hierarchy(design, hierarchy)
        path = output_dir / file_name_for_hierarchy(hierarchy)
        path.write_text(text, encoding="utf-8", newline="\n")
        files.append(path)
    return files


def _all_hierarchies(design: Design, top: str) -> list[str]:
    hierarchies = {top}
    for inst in design.instances:
        parts = inst.hierarchy.split(".")
        for i in range(1, len(parts) + 1):
            hierarchies.add(".".join(parts[:i]))
    for net in design.nets:
        parts = net.hierarchy.split(".")
        for i in range(1, len(parts) + 1):
            hierarchies.add(".".join(parts[:i]))
    return sorted(hierarchies, key=lambda h: (h.count("."), h))


def _emit_hierarchy(design: Design, hierarchy: str) -> str:
    module_name = module_name_for_hierarchy(hierarchy)
    ports = _module_ports(design, hierarchy)
    lines = ["// Generated by verilog_generator.", f"module {module_name} ("]
    if ports:
        for idx, net in enumerate(ports):
            comma = "," if idx < len(ports) - 1 else ""
            lines.append(f"    {_port_decl(net)}{comma}")
    lines.append(");")
    lines.append("")

    local_nets = [n for n in design.nets if n.hierarchy == hierarchy and not n.port_direction]
    for net in sorted(local_nets, key=lambda n: n.name):
        lines.append(_wire_decl(net))
    if local_nets:
        lines.append("")

    child_text = _emit_child_hierarchy_instances(design, hierarchy)
    if child_text:
        lines.extend(child_text)
        lines.append("")

    instance_text = _emit_module_instances(design, hierarchy)
    if instance_text:
        lines.extend(instance_text)
        lines.append("")

    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def _module_ports(design: Design, hierarchy: str) -> list[Net]:
    ports = {n.name: n for n in design.nets if n.hierarchy == hierarchy and n.port_direction}
    for child in _immediate_child_hierarchies(design, hierarchy):
        for net in design.nets:
            if net.hierarchy == child and net.port_direction:
                ports.setdefault(net.name, net)
    return sorted(ports.values(), key=lambda n: n.name)


def _immediate_child_hierarchies(design: Design, hierarchy: str) -> list[str]:
    prefix = f"{hierarchy}."
    children = set()
    for inst in design.instances:
        if inst.hierarchy.startswith(prefix):
            rest = inst.hierarchy[len(prefix):]
            first = rest.split(".", 1)[0]
            children.add(f"{hierarchy}.{first}")
    return sorted(children)


def _emit_child_hierarchy_instances(design: Design, hierarchy: str) -> list[str]:
    lines: list[str] = []
    for child in _immediate_child_hierarchies(design, hierarchy):
        child_inst = sanitize_identifier(child.split(".")[-1])
        child_module = module_name_for_hierarchy(child)
        ports = [n for n in design.nets if n.hierarchy == child and n.port_direction]
        lines.append(f"{child_module} {child_inst} (")
        for idx, net in enumerate(sorted(ports, key=lambda n: n.name)):
            comma = "," if idx < len(ports) - 1 else ""
            lines.append(f"    .{net.name}({net.name}){comma}")
        lines.append(");")
    return lines


def _emit_module_instances(design: Design, hierarchy: str) -> list[str]:
    modules = {m.name: m for m in design.modules}
    nets = {(n.hierarchy, n.name): n for n in design.nets}
    lines: list[str] = []
    for inst in sorted([i for i in design.instances if i.hierarchy == hierarchy], key=lambda i: i.name):
        module = modules.get(inst.module)
        if not module:
            continue
        conn_by_port = {c.port: c for c in design.connections if c.hierarchy == hierarchy and c.instance == inst.name}
        pre_lines: list[str] = []
        post_lines: list[str] = []
        port_lines: list[str] = []
        for port in module.ports:
            conn = conn_by_port.get(port.name)
            if not conn:
                continue
            net = nets.get((hierarchy, conn.net))
            if not net:
                continue
            adapt = _adapt_connection(inst, module, port, net)
            pre_lines.extend(adapt.warnings)
            pre_lines.extend(adapt.decls)
            post_lines.extend(adapt.assigns)
            port_lines.append(f"    .{port.name}({adapt.port_net or net.name})")
        lines.extend(pre_lines)
        lines.extend(_instance_header(inst, module))
        for idx, pline in enumerate(port_lines):
            comma = "," if idx < len(port_lines) - 1 else ""
            lines.append(f"{pline}{comma}")
        lines.append(");")
        lines.extend(post_lines)
        lines.append("")
    return lines


def _instance_header(inst: Instance, module: Module) -> list[str]:
    params = [(p.name, inst.parameters[p.name]) for p in module.parameters if p.name in inst.parameters]
    if not params:
        return [f"{module.name} {inst.name} ("]
    lines = [f"{module.name} #("]
    for idx, (name, value) in enumerate(params):
        comma = "," if idx < len(params) - 1 else ""
        lines.append(f"    .{name}({value}){comma}")
    lines.append(f") {inst.name} (")
    return lines


def _adapt_connection(inst: Instance, module: Module, port: Port, net: Net) -> Adaptation:
    port_width = resolve_port_width(port, inst, module) or net.width
    if port_width == net.width:
        return Adaptation(port_net=net.name)
    temp = f"{net.name}_to_{inst.name}_{port.name}"
    temp = sanitize_identifier(temp)
    adapt = Adaptation(port_net=temp)
    if port.direction == "input":
        adapt.warnings.append(f"// WARNING: auto width adapt {net.name}[{net.width}] to {inst.name}.{port.name}[{port_width}]")
        adapt.decls.append(_wire_decl_from_parts(temp, port_width, net.signed))
        adapt.assigns.append(f"assign {temp} = {_adapt_expr(net.name, net.width, port_width, net.signed)};")
    else:
        adapt.warnings.append(f"// WARNING: auto width adapt {inst.name}.{port.name}[{port_width}] to {net.name}[{net.width}]")
        adapt.decls.append(_wire_decl_from_parts(temp, port_width, port.signed))
        adapt.assigns.append(f"assign {net.name} = {_adapt_expr(temp, port_width, net.width, port.signed)};")
    return adapt


def _adapt_expr(name: str, from_width: int, to_width: int, signed: bool) -> str:
    if from_width == to_width:
        return name
    if from_width > to_width:
        return f"{name}[{to_width - 1}:0]"
    pad = to_width - from_width
    fill = f"{name}[{from_width - 1}]" if signed else "1'b0"
    return f"{{{{{pad}{{{fill}}}}}, {name}}}"


def _port_decl(net: Net) -> str:
    signed = " signed" if net.signed else ""
    return f"{net.port_direction}{signed}{width_range(net.width)} {net.name}"


def _wire_decl(net: Net) -> str:
    return _wire_decl_from_parts(net.name, net.width, net.signed)


def _wire_decl_from_parts(name: str, width: int, signed: bool = False) -> str:
    signed_text = " signed" if signed else ""
    return f"wire{signed_text}{width_range(width)} {name};"

